import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Footer";
import Providers from "./components/Providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Navbar = () => {
  return (
    <nav className="border-b p-6">
      <p className="text-4xl font-bold">Next.js + Tailwind CSS</p>
      <ul className="flex gap-4 items-center">
        <li>
          <a
            href="https://nextjs.org/docs"
            className="text-blue-600 hover:text-blue-900"
          >
            Docs &rarr;
          </a>
        </li>
        <li>
          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className="text-blue-600 hover:text-blue-900"
          >
            Examples &rarr;
          </a>
        </li>
        <li>
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="text-blue-600 hover:text-blue-900"
          >
            Deploy &rarr;
          </a>
        </li>
      </ul>
    </nav>)
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <Providers >
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
