import type { RestaurantBase } from "@/services/types";
export const norrlandsData: RestaurantBase[] = [
    {
        name: "Churrascaria BBQ",
        description: "En brasiliansk grillbuffé där du kan njuta av olika sorters kött serverat vid bordet.",
        address: "Storgatan 15, Umeå",
        type: "BUFFET",
        price: 399,
        lunchPrice: 0,
        eveningPrice: 399,
        weekendPrice: 399,
        rating: 4.6,
        website: "https://churrascariabbq.se",
        imageUrl: "https://churrascariabbq.se/images/restaurant.jpg",
        longitude: 20.2630,
        latitude: 63.8258,
        foodBadges: ["BRAZILIAN", "BUFFET"]
    },
    {
        name: "Storforsens Lunchbuffé",
        description: "En vällagad lunchbuffé som serveras varje dag med två varmrätter, salladsbuffé och hembakat bröd. Njut av maten med en fantastisk utsikt.",
        address: "Storforsen, 942 91 Älvsbyn",
        type: "BUFFET",
        price: 145,
        lunchPrice: 145,
        eveningPrice: 0,
        weekendPrice: 0,
        rating: 4.5,
        website: "https://www.storforsen.se/lunchbuffe/",
        imageUrl: "https://www.storforsen.se/images/restaurant.jpg",
        longitude: 20.0808,
        latitude: 65.6475,
        foodBadges: ["SWEDISH", "BUFFET"]
    },
    {
        name: "Café UH",
        description: "Erbjuder ett stort utbud av lunchrätter och bufféer med veganska alternativ i Örnsköldsvik.",
        address: "Storgatan 12, 891 31 Örnsköldsvik",
        type: "BUFFET",
        price: 120,
        lunchPrice: 120,
        eveningPrice: 0,
        weekendPrice: 0,
        rating: 4.3,
        website: "https://cafeuh.se/cafe-uh-vart-utbud-fika-mackor-sallader-presentkort/",
        imageUrl: "https://cafeuh.se/images/restaurant.jpg",
        longitude: 19.1821,
        latitude: 63.2896,
        foodBadges: ["VEGETARIAN", "BUFFET"]
    },
    {
        name: "Pins Thairestaurang",
        description: "Serverar genuin thailändsk mat med en stor buffé av friterade och wokade rätter.",
        address: "Rådhusesplanaden 5, Umeå",
        type: "BUFFET",
        price: 199,
        lunchPrice: 199,
        eveningPrice: 0,
        weekendPrice: 0,
        rating: 4.4,
        website: "https://www.pinsthairestaurang.se",
        imageUrl: "https://www.pinsthairestaurang.se/images/restaurant.jpg",
        longitude: 20.2630,
        latitude: 63.8258,
        foodBadges: ["THAI", "BUFFET"]
    },
    {
        name: "Droskan",
        description: "En restaurang som erbjuder allt från dagens lunch till kvällens generösa bufféer.",
        address: "Umeå, Västerbotten ",
        type: "BUFFET ",
        price: 250,
        lunchPrice: 250,
        rating: 4.6,
        website: "https://droskan.se/",
        imageUrl: "https://droskan.se/images/restaurant.jpg",
        longitude: 20.2632,
        latitude: 63.8259,
        foodBadges: ["SWEDISH", "BUFFET"]
    },
]

export const malmöData: RestaurantBase[] = [
    {
        name: "Mister French",
        description: "Fisk- och skaldjursbrunch med ett stort utbud av sötsaker och brunchcocktails.",
        address: "Lilla Nygatan 5, Malmö ",
        type: "BUFFET ",
        price: 495,
        lunchPrice: 0,
        eveningPrice: 0,
        weekendPrice: 495,
        rating: 4.7,
        website: "https://misterfrench.se/",
        imageUrl: "https://misterfrench.se/images/restaurant.jpg",
        longitude: 13.0038,
        latitude: 55.6050,
        foodBadges: ["SEAFOOD", "BUFFET"]
    },
]
